package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attractions generated by hbm2java
 */
@Entity
@Table(name = "attractions", catalog = "traveling")
public class Attractions implements java.io.Serializable {

	private Integer idAttraction;
	private Cities cities;
	private String attractionName;
	private String attDescription;
	private Set<Routes> routeses = new HashSet<Routes>(0);

	public Attractions() {
	}

	public Attractions(Cities cities, String attractionName) {
		this.cities = cities;
		this.attractionName = attractionName;
	}

	public Attractions(Cities cities, String attractionName, String attDescription, Set<Routes> routeses) {
		this.cities = cities;
		this.attractionName = attractionName;
		this.attDescription = attDescription;
		this.routeses = routeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_attraction", unique = true, nullable = false)
	public Integer getIdAttraction() {
		return this.idAttraction;
	}

	public void setIdAttraction(Integer idAttraction) {
		this.idAttraction = idAttraction;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_city", nullable = false)
	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

	@Column(name = "attraction_name", nullable = false, length = 60)
	public String getAttractionName() {
		return this.attractionName;
	}

	public void setAttractionName(String attractionName) {
		this.attractionName = attractionName;
	}

	@Column(name = "att_description", length = 65535)
	public String getAttDescription() {
		return this.attDescription;
	}

	public void setAttDescription(String attDescription) {
		this.attDescription = attDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attractions")
	public Set<Routes> getRouteses() {
		return this.routeses;
	}

	public void setRouteses(Set<Routes> routeses) {
		this.routeses = routeses;
	}

}
