package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", catalog = "traveling")
public class Cities implements java.io.Serializable {

	private Integer idCity;
	private Countries countries;
	private String cityName;
	private Set<Tickets> ticketsesForIdCityTo = new HashSet<Tickets>(0);
	private Set<Hotels> hotelses = new HashSet<Hotels>(0);
	private Set<Tickets> ticketsesForIdCityFrom = new HashSet<Tickets>(0);
	private Set<Attractions> attractionses = new HashSet<Attractions>(0);
	private Set<Restaurants> restaurantses = new HashSet<Restaurants>(0);

	public Cities() {
	}

	public Cities(Countries countries, String cityName) {
		this.countries = countries;
		this.cityName = cityName;
	}

	public Cities(Countries countries, String cityName, Set<Tickets> ticketsesForIdCityTo, Set<Hotels> hotelses,
			Set<Tickets> ticketsesForIdCityFrom, Set<Attractions> attractionses, Set<Restaurants> restaurantses) {
		this.countries = countries;
		this.cityName = cityName;
		this.ticketsesForIdCityTo = ticketsesForIdCityTo;
		this.hotelses = hotelses;
		this.ticketsesForIdCityFrom = ticketsesForIdCityFrom;
		this.attractionses = attractionses;
		this.restaurantses = restaurantses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_city", unique = true, nullable = false)
	public Integer getIdCity() {
		return this.idCity;
	}

	public void setIdCity(Integer idCity) {
		this.idCity = idCity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_country", nullable = false)
	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	@Column(name = "city_name", nullable = false, length = 50)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "citiesByIdCityTo")
	public Set<Tickets> getTicketsesForIdCityTo() {
		return this.ticketsesForIdCityTo;
	}

	public void setTicketsesForIdCityTo(Set<Tickets> ticketsesForIdCityTo) {
		this.ticketsesForIdCityTo = ticketsesForIdCityTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cities")
	public Set<Hotels> getHotelses() {
		return this.hotelses;
	}

	public void setHotelses(Set<Hotels> hotelses) {
		this.hotelses = hotelses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "citiesByIdCityFrom")
	public Set<Tickets> getTicketsesForIdCityFrom() {
		return this.ticketsesForIdCityFrom;
	}

	public void setTicketsesForIdCityFrom(Set<Tickets> ticketsesForIdCityFrom) {
		this.ticketsesForIdCityFrom = ticketsesForIdCityFrom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cities")
	public Set<Attractions> getAttractionses() {
		return this.attractionses;
	}

	public void setAttractionses(Set<Attractions> attractionses) {
		this.attractionses = attractionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cities")
	public Set<Restaurants> getRestaurantses() {
		return this.restaurantses;
	}

	public void setRestaurantses(Set<Restaurants> restaurantses) {
		this.restaurantses = restaurantses;
	}

}
