package dbmodel;
// Generated May 9, 2020 2:31:40 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Continents generated by hbm2java
 */
@Entity
@Table(name = "continents", catalog = "traveling", uniqueConstraints = @UniqueConstraint(columnNames = "continent_name"))
public class Continents implements java.io.Serializable {

	private Integer idContinent;
	private String continentName;
	private Set<Countries> countrieses = new HashSet<Countries>(0);

	public Continents() {
	}

	public Continents(String continentName) {
		this.continentName = continentName;
	}

	public Continents(String continentName, Set<Countries> countrieses) {
		this.continentName = continentName;
		this.countrieses = countrieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_continent", unique = true, nullable = false)
	public Integer getIdContinent() {
		return this.idContinent;
	}

	public void setIdContinent(Integer idContinent) {
		this.idContinent = idContinent;
	}

	@Column(name = "continent_name", unique = true, nullable = false, length = 50)
	public String getContinentName() {
		return this.continentName;
	}

	public void setContinentName(String continentName) {
		this.continentName = continentName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "continents")
	public Set<Countries> getCountrieses() {
		return this.countrieses;
	}

	public void setCountrieses(Set<Countries> countrieses) {
		this.countrieses = countrieses;
	}

}
