package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", catalog = "traveling")
public class Countries implements java.io.Serializable {

	private Integer idCountry;
	private Continents continents;
	private String countryName;
	private String capital;
	private Integer population;
	private Integer area;
	private Set<Cities> citieses = new HashSet<Cities>(0);

	public Countries() {
	}

	public Countries(Continents continents, String countryName, String capital) {
		this.continents = continents;
		this.countryName = countryName;
		this.capital = capital;
	}

	public Countries(Continents continents, String countryName, String capital, Integer population, Integer area,
			Set<Cities> citieses) {
		this.continents = continents;
		this.countryName = countryName;
		this.capital = capital;
		this.population = population;
		this.area = area;
		this.citieses = citieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_country", unique = true, nullable = false)
	public Integer getIdCountry() {
		return this.idCountry;
	}

	public void setIdCountry(Integer idCountry) {
		this.idCountry = idCountry;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_continent", nullable = false)
	public Continents getContinents() {
		return this.continents;
	}

	public void setContinents(Continents continents) {
		this.continents = continents;
	}

	@Column(name = "country_name", nullable = false, length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "capital", nullable = false, length = 50)
	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	@Column(name = "population")
	public Integer getPopulation() {
		return this.population;
	}

	public void setPopulation(Integer population) {
		this.population = population;
	}

	@Column(name = "area")
	public Integer getArea() {
		return this.area;
	}

	public void setArea(Integer area) {
		this.area = area;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countries")
	public Set<Cities> getCitieses() {
		return this.citieses;
	}

	public void setCitieses(Set<Cities> citieses) {
		this.citieses = citieses;
	}

}
