package dbmodel;
// Generated May 9, 2020 2:31:40 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cuisine generated by hbm2java
 */
@Entity
@Table(name = "cuisine", catalog = "traveling", uniqueConstraints = @UniqueConstraint(columnNames = "cuisine_type"))
public class Cuisine implements java.io.Serializable {

	private Integer idCuisine;
	private String cuisineType;
	private Set<RestCuis> restCuises = new HashSet<RestCuis>(0);

	public Cuisine() {
	}

	public Cuisine(String cuisineType) {
		this.cuisineType = cuisineType;
	}

	public Cuisine(String cuisineType, Set<RestCuis> restCuises) {
		this.cuisineType = cuisineType;
		this.restCuises = restCuises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cuisine", unique = true, nullable = false)
	public Integer getIdCuisine() {
		return this.idCuisine;
	}

	public void setIdCuisine(Integer idCuisine) {
		this.idCuisine = idCuisine;
	}

	@Column(name = "cuisine_type", unique = true, nullable = false, length = 50)
	public String getCuisineType() {
		return this.cuisineType;
	}

	public void setCuisineType(String cuisineType) {
		this.cuisineType = cuisineType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuisine")
	public Set<RestCuis> getRestCuises() {
		return this.restCuises;
	}

	public void setRestCuises(Set<RestCuis> restCuises) {
		this.restCuises = restCuises;
	}

}
