package dbmodel;
// Generated May 9, 2020 2:31:40 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Hotels generated by hbm2java
 */
@Entity
@Table(name = "hotels", catalog = "traveling", uniqueConstraints = @UniqueConstraint(columnNames = { "hotel_name",
		"id_city", "address" }))
public class Hotels implements java.io.Serializable {

	private Integer idHotel;
	private Cities cities;
	private String hotelName;
	private String address;
	private BigDecimal rating;
	private Integer amountOfStars;
	private String website;

	public Hotels() {
	}

	public Hotels(Cities cities, String hotelName, String address) {
		this.cities = cities;
		this.hotelName = hotelName;
		this.address = address;
	}

	public Hotels(Cities cities, String hotelName, String address, BigDecimal rating, Integer amountOfStars,
			String website) {
		this.cities = cities;
		this.hotelName = hotelName;
		this.address = address;
		this.rating = rating;
		this.amountOfStars = amountOfStars;
		this.website = website;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_hotel", unique = true, nullable = false)
	public Integer getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(Integer idHotel) {
		this.idHotel = idHotel;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_city", nullable = false)
	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

	@Column(name = "hotel_name", nullable = false, length = 60)
	public String getHotelName() {
		return this.hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "rating", precision = 5)
	public BigDecimal getRating() {
		return this.rating;
	}

	public void setRating(BigDecimal rating) {
		this.rating = rating;
	}

	@Column(name = "amount_of_stars")
	public Integer getAmountOfStars() {
		return this.amountOfStars;
	}

	public void setAmountOfStars(Integer amountOfStars) {
		this.amountOfStars = amountOfStars;
	}

	@Column(name = "website", length = 60)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

}
