package dbmodel;
// Generated May 9, 2020 2:31:40 PM by Hibernate Tools 5.2.12.Final

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlaceStats generated by hbm2java
 */
@Entity
@Table(name = "place_stats", catalog = "traveling")
public class PlaceStats implements java.io.Serializable {

	private Integer idPlaceStats;
	private PlaceTypes placeTypes;
	private int placeId;
	private Integer idUser;
	private Timestamp collectedAt;

	public PlaceStats() {
	}

	public PlaceStats(PlaceTypes placeTypes, int placeId, Timestamp collectedAt) {
		this.placeTypes = placeTypes;
		this.placeId = placeId;
		this.collectedAt = collectedAt;
	}

	public PlaceStats(PlaceTypes placeTypes, int placeId, Integer idUser, Timestamp collectedAt) {
		this.placeTypes = placeTypes;
		this.placeId = placeId;
		this.idUser = idUser;
		this.collectedAt = collectedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_place_stats", unique = true, nullable = false)
	public Integer getIdPlaceStats() {
		return this.idPlaceStats;
	}

	public void setIdPlaceStats(Integer idPlaceStats) {
		this.idPlaceStats = idPlaceStats;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_place_type", nullable = false)
	public PlaceTypes getPlaceTypes() {
		return this.placeTypes;
	}

	public void setPlaceTypes(PlaceTypes placeTypes) {
		this.placeTypes = placeTypes;
	}

	@Column(name = "place_id", nullable = false)
	public int getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(int placeId) {
		this.placeId = placeId;
	}

	@Column(name = "id_user")
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "collected_at", nullable = false, length = 19)
	public Date getCollectedAt() {
		return this.collectedAt;
	}

	public void setCollectedAt(Timestamp collectedAt) {
		this.collectedAt = collectedAt;
	}

}
