package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RestCuis generated by hbm2java
 */
@Entity
@Table(name = "rest_cuis", catalog = "traveling", uniqueConstraints = @UniqueConstraint(columnNames = { "id_restaurant",
		"id_cuisine" }))
public class RestCuis implements java.io.Serializable {

	private Integer idRestCuis;
	private Cuisine cuisine;
	private Restaurants restaurants;

	public RestCuis() {
	}

	public RestCuis(Cuisine cuisine, Restaurants restaurants) {
		this.cuisine = cuisine;
		this.restaurants = restaurants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_rest_cuis", unique = true, nullable = false)
	public Integer getIdRestCuis() {
		return this.idRestCuis;
	}

	public void setIdRestCuis(Integer idRestCuis) {
		this.idRestCuis = idRestCuis;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cuisine", nullable = false)
	public Cuisine getCuisine() {
		return this.cuisine;
	}

	public void setCuisine(Cuisine cuisine) {
		this.cuisine = cuisine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_restaurant", nullable = false)
	public Restaurants getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Restaurants restaurants) {
		this.restaurants = restaurants;
	}

}
