package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Restaurants generated by hbm2java
 */
@Entity
@Table(name = "restaurants", catalog = "traveling")
public class Restaurants implements java.io.Serializable {

	private Integer idRestaurant;
	private Cities cities;
	private String restName;
	private String address;
	private BigDecimal rating;
	private String website;
	private Set<Routes> routeses = new HashSet<Routes>(0);
	private Set<RestCuis> restCuises = new HashSet<RestCuis>(0);

	public Restaurants() {
	}

	public Restaurants(Cities cities, String restName, String address) {
		this.cities = cities;
		this.restName = restName;
		this.address = address;
	}

	public Restaurants(Cities cities, String restName, String address, BigDecimal rating, String website,
			Set<Routes> routeses, Set<RestCuis> restCuises) {
		this.cities = cities;
		this.restName = restName;
		this.address = address;
		this.rating = rating;
		this.website = website;
		this.routeses = routeses;
		this.restCuises = restCuises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_restaurant", unique = true, nullable = false)
	public Integer getIdRestaurant() {
		return this.idRestaurant;
	}

	public void setIdRestaurant(Integer idRestaurant) {
		this.idRestaurant = idRestaurant;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_city", nullable = false)
	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

	@Column(name = "rest_name", nullable = false, length = 60)
	public String getRestName() {
		return this.restName;
	}

	public void setRestName(String restName) {
		this.restName = restName;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "rating", precision = 5)
	public BigDecimal getRating() {
		return this.rating;
	}

	public void setRating(BigDecimal rating) {
		this.rating = rating;
	}

	@Column(name = "website", length = 60)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurants")
	public Set<Routes> getRouteses() {
		return this.routeses;
	}

	public void setRouteses(Set<Routes> routeses) {
		this.routeses = routeses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "restaurants")
	public Set<RestCuis> getRestCuises() {
		return this.restCuises;
	}

	public void setRestCuises(Set<RestCuis> restCuises) {
		this.restCuises = restCuises;
	}

}
