package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tickets generated by hbm2java
 */
@Entity
@Table(name = "tickets", catalog = "traveling")
public class Tickets implements java.io.Serializable {

	private Integer idTicket;
	private Calendar calendarByIdCalendarEnd;
	private Calendar calendarByIdCalendarStart;
	private Cities citiesByIdCityTo;
	private Cities citiesByIdCityFrom;
	private Transport transport;

	public Tickets() {
	}

	public Tickets(Calendar calendarByIdCalendarEnd, Calendar calendarByIdCalendarStart, Cities citiesByIdCityTo,
			Cities citiesByIdCityFrom) {
		this.calendarByIdCalendarEnd = calendarByIdCalendarEnd;
		this.calendarByIdCalendarStart = calendarByIdCalendarStart;
		this.citiesByIdCityTo = citiesByIdCityTo;
		this.citiesByIdCityFrom = citiesByIdCityFrom;
	}

	public Tickets(Calendar calendarByIdCalendarEnd, Calendar calendarByIdCalendarStart, Cities citiesByIdCityTo,
			Cities citiesByIdCityFrom, Transport transport) {
		this.calendarByIdCalendarEnd = calendarByIdCalendarEnd;
		this.calendarByIdCalendarStart = calendarByIdCalendarStart;
		this.citiesByIdCityTo = citiesByIdCityTo;
		this.citiesByIdCityFrom = citiesByIdCityFrom;
		this.transport = transport;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ticket", unique = true, nullable = false)
	public Integer getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(Integer idTicket) {
		this.idTicket = idTicket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_calendar_end", nullable = false)
	public Calendar getCalendarByIdCalendarEnd() {
		return this.calendarByIdCalendarEnd;
	}

	public void setCalendarByIdCalendarEnd(Calendar calendarByIdCalendarEnd) {
		this.calendarByIdCalendarEnd = calendarByIdCalendarEnd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_calendar_start", nullable = false)
	public Calendar getCalendarByIdCalendarStart() {
		return this.calendarByIdCalendarStart;
	}

	public void setCalendarByIdCalendarStart(Calendar calendarByIdCalendarStart) {
		this.calendarByIdCalendarStart = calendarByIdCalendarStart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_city_to", nullable = false)
	public Cities getCitiesByIdCityTo() {
		return this.citiesByIdCityTo;
	}

	public void setCitiesByIdCityTo(Cities citiesByIdCityTo) {
		this.citiesByIdCityTo = citiesByIdCityTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_city_from", nullable = false)
	public Cities getCitiesByIdCityFrom() {
		return this.citiesByIdCityFrom;
	}

	public void setCitiesByIdCityFrom(Cities citiesByIdCityFrom) {
		this.citiesByIdCityFrom = citiesByIdCityFrom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_transport")
	public Transport getTransport() {
		return this.transport;
	}

	public void setTransport(Transport transport) {
		this.transport = transport;
	}

}
