package dbmodel;
// Generated May 9, 2020 2:31:40 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Transport generated by hbm2java
 */
@Entity
@Table(name = "transport", catalog = "traveling", uniqueConstraints = @UniqueConstraint(columnNames = "transport_name"))
public class Transport implements java.io.Serializable {

	private Integer idTransport;
	private String transportName;
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);

	public Transport() {
	}

	public Transport(String transportName) {
		this.transportName = transportName;
	}

	public Transport(String transportName, Set<Tickets> ticketses) {
		this.transportName = transportName;
		this.ticketses = ticketses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_transport", unique = true, nullable = false)
	public Integer getIdTransport() {
		return this.idTransport;
	}

	public void setIdTransport(Integer idTransport) {
		this.idTransport = idTransport;
	}

	@Column(name = "transport_name", unique = true, nullable = false, length = 50)
	public String getTransportName() {
		return this.transportName;
	}

	public void setTransportName(String transportName) {
		this.transportName = transportName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transport")
	public Set<Tickets> getTicketses() {
		return this.ticketses;
	}

	public void setTicketses(Set<Tickets> ticketses) {
		this.ticketses = ticketses;
	}

}
