package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "traveling", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class Users implements java.io.Serializable {

	private Integer idUser;
	private Roles roles;
	private String lastName;
	private String firstName;
	private String mail;
	private String login;
	private String UPassword;
	private Set<UsersRoutes> usersRouteses = new HashSet<UsersRoutes>(0);

	public Users() {
	}

	public Users(Roles roles, String lastName, String firstName, String login, String UPassword) {
		this.roles = roles;
		this.lastName = lastName;
		this.firstName = firstName;
		this.login = login;
		this.UPassword = UPassword;
	}

	public Users(Roles roles, String lastName, String firstName, String mail, String login, String UPassword,
			Set<UsersRoutes> usersRouteses) {
		this.roles = roles;
		this.lastName = lastName;
		this.firstName = firstName;
		this.mail = mail;
		this.login = login;
		this.UPassword = UPassword;
		this.usersRouteses = usersRouteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_user", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_role", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "last_name", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "mail", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "login", unique = true, nullable = false, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "u_password", nullable = false, length = 50)
	public String getUPassword() {
		return this.UPassword;
	}

	public void setUPassword(String UPassword) {
		this.UPassword = UPassword;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UsersRoutes> getUsersRouteses() {
		return this.usersRouteses;
	}

	public void setUsersRouteses(Set<UsersRoutes> usersRouteses) {
		this.usersRouteses = usersRouteses;
	}

}
