package dbmodel;
// Generated Apr 27, 2020 7:51:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsersRoutes generated by hbm2java
 */
@Entity
@Table(name = "users_routes", catalog = "traveling", uniqueConstraints = @UniqueConstraint(columnNames = { "id_user",
		"id_route" }))
public class UsersRoutes implements java.io.Serializable {

	private Integer idUsersRoutes;
	private Routes routes;
	private Users users;

	public UsersRoutes() {
	}

	public UsersRoutes(Routes routes, Users users) {
		this.routes = routes;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_users_routes", unique = true, nullable = false)
	public Integer getIdUsersRoutes() {
		return this.idUsersRoutes;
	}

	public void setIdUsersRoutes(Integer idUsersRoutes) {
		this.idUsersRoutes = idUsersRoutes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_route", nullable = false)
	public Routes getRoutes() {
		return this.routes;
	}

	public void setRoutes(Routes routes) {
		this.routes = routes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
